### ISSUE TITLE
Post-install fixes on i386 gnu/*nux

### ISSUE THREAD

**Issue by pierstu** [cleary/ansible-tidalcycles#12]
Thanks again for the ansible script. As said on Discord, i've installed it again last week on a fresher Devuan 4 install for i386.
After a tidal_vim installation, i've encountered issues with the tidalvim command.

In ghci
```haskell 
Prelude> import Sound.Tidal.Cabal

<no location info>: error:
  Could not find module 'Sound.Tidal.Cabal'
```
In tmux :
```haskell 
<interactive>:0:1: error:
  Not in scope: `Paths_tidal.getDataDir`
  No module named 'Paths_tidal' is imported.
```
## what worked for me
- delete all tidal-related dirs in ~/.cabal/share, ~/.cabal/lib (there were 2 tidal-1.8.0-longhash already, which could maybe have lead to a conflict?), ~/.cabal/packages/hackage.haskell.org
- run `cabal v1-update` then `cabal v1-install tidal`
- check in Emacs > 26 (else you'll struggle with the GNU keyring update) if it works after editing `~/.emacs`, installing the Melpa package, and setting things up. 
- If it does, head up to ~/.vim/plugged/vim-tidal, run `sudo make uninstall`, crawl up a dir via `cd ../` then `sudo make install` again.

Have a nice weekend

**Comment by cleary** [comment]
I'm going to close this, unfortunately i386 support for the moment has stopped at tidal 1.8.1 (we are now at 1.9.3) 

Follow along here:
https://github.com/tidalcycles/Tidal/issues/957
