### ISSUE TITLE
Failure to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by ivanperez-keera** [cleary/ansible-tidalcycles#21]
Running:

```
sudo ansible-playbook --connection=local -i localhost, tidal_vim.play.yml
```

Produces the following error:

```
TASK [roles/tidal : install ansible task dependencies (debian)] ****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: unknown reason"}
```

The same happens with:
```
sudo ansible-playbook --connection=local -i localhost, tidal.play.yml
```

**Comment by cleary** [comment]
Hi,
Thanks for your issue report - apologies for the late response:

This task is attempting to run the following:
```
sudo apt update
```
 - do you get an error when you run the task manually?

**Comment by cleary** [comment]
closing due to non-response, please feel free to ask again if you're still having issues, or catch me on the tidal forums/discord
