### ISSUE TITLE
nuke option(s) for userspace packages (.cabal, .ghc etc)?

### ISSUE THREAD

**Issue by cleary** [cleary/ansible-tidalcycles#7]
Hi Alex - just posting this for discussion when you get some free space/time (no urgency)

It seems that getting stuck in haskell dependency hell is relatively common, going by reports on the forums. The only way I know of to resolve this is by nuking directories in my userspace, and re-installing -

When in cabal dependency hell, is there a better way out than a nuke-those-dirs option?

Either way, do you think there's value offering an opt-in (and potentially slightly hidden) fix/nuke option as part of this ansible setup/set of tasks?

**Comment by yaxu** [comment]
I've seen this command used:
```
cabal user-config init -f
```
E.g. it's recommended here: https://www.haskell.org/platform/windows.html

However I'm not sure what it does. I just ran it and tidal is still installed. Maybe it resets 'new style' cabal stuff but not 'old style'.

Indeed there's _massive_ confusion around old and new style cabal installs, with conflicts between old and new, and unresolved bugs. For ansible I'd even consider supporting an older version of ghc / cabal that uses the old style cabal as default..

So the short answer is I don't know.. Maybe we should raise an issue on the cabal repo asking about it?

**Comment by cleary** [comment]
Thanks for the reply - I've had a bit of a poke around to see if anyone has built an ansible module for cabal/haskell (not as yet as far as I can find).
I did find another package manager for haskell called [stack](https://docs.haskellstack.org/en/stable/README/) which may be a possibility for being more reliable - I haven't dug any deeper though, just flagging it for when I look back at this issue :)

**Comment by yaxu** [comment]
Did you get anywhere with stack? It might be a bit more reliable, as it involves installing tidal against a frozen set of packages.

**Comment by cleary** [comment]
huh I'd forgotten all about it - I did a big sprint on this repo in July, but since then I've been focussing on actually trying to make some music/learn tidal in a bit more detail ...
Happy to have a look, probably after the New Moon gig - also happy if you wanted to take a look first too :)
